HR.Web_UI/HR.Web_UI/Controllers/CommonController.cs
using HR.DataAccess.GLOBAL.UnityOfWorks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EF_R = HR.DataAccess.EF.Repositories;
using NH_R = HR.DataAccess.NH.Repositories;
using EF_U = HR.DataAccess.EF.UnityOfWorks;
using NH_U = HR.DataAccess.NH.UnityOfWorks;
using HR.Core.Models.RepoModels;
using HR.Web_UI.Services.ServicesInferface;
using HR.Web_UI.Models.ViewModels.HR;
using PagedList;

namespace HR.Web_UI.Controllers
{
    /// <summary>
    /// Tutaj zawarte sa akcje dostepne dla nie zalogowanego uzytkownika tj. strona startowa, informacje o firmie, materialy promocyjne
    /// </summary>
    public class CommonController : BaseController
    {
        ICommonService commonService;

        public CommonController(ICommonService _commonService)
        {
            this.commonService = _commonService;
        }

        // GET: Common
        /// <summary>
        /// Strona startowa z newsami
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //dodac prosty view model i obrobic widok
            return View();
        }

        public ActionResult InformacjeOFirmie()
        {
            return View();
        }

        public ActionResult DisplayPromotialMaterials(string Sorting_Order, string Search_Data, string Filter_Value, int? Page_No, string OrderType)
        {
            var materials = commonService.GetAllMaterials();

            int Size_Of_Page = 10;
            int No_Of_Page = (Page_No ?? 1);

            PromotialMaterialViewModel pVM = new PromotialMaterialViewModel();
            pVM.Materials = materials.OrderByDescending(p => p.Id).ToPagedList(No_Of_Page, Size_Of_Page);
            pVM.PageCount = (int)Math.Ceiling((double)materials.Count() / Size_Of_Page);
            pVM.PageNumber = Page_No ?? 1;

            return View(pVM);
        }

        public ActionResult AboutAuthor()
        {
            return View();
        }


    }
}

HR.Web_UI/HR.Web_UI/Controllers/WorkerController.cs
using HR.Web_UI.Services.ServicesInferface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HR.Web_UI.Models.ViewModels.Account;
using HR.Core.Models;
using PagedList;
using HR.Web_UI.Models.ViewModels.HR;

namespace HR.Web_UI.Controllers
{
    //[Authorize(Roles = "Pracownik")]
    public class WorkerController : BaseController
    {
        IWorkerService workerService;
        IAccountService accountService;

        public WorkerController(IWorkerService _workerService, IAccountService _accountService)
        {
            this.workerService = _workerService;
            this.accountService = _accountService;

            //CurrentUser = CurrentUser ?? accountService.GetUserByName();
        }

        // GET: Worker
        public ActionResult Index()
        {
            var x = CurrentUser;
            return View();
        }

        public ActionResult DisplayTraningsMaterials()
        {
            //workerService.GetAllMaterials();

            return View();
        }

        public ActionResult DisplayWorkBoard()
        {
            //dzisiaj przyszedles do pracy o...
            return View();
        }

        public ActionResult DisplayDocuments()
        {
            return View();
        }

        public ActionResult DisplayCharts()
        {
            return View();
        }

        public ActionResult ManageAccount()
        {
            var x = workerService.GetAccount(CurrentUser.AccountId);
            if (Request.IsAjaxRequest())
            {
                return PartialView(x);
            }
            return View(x);
        }

        public ActionResult ChangePassword(long id)
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            else
            {
                return View();
            }
            
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordViewModel chpVM)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("ManageAccount");
            }
            return View();
        }

        public ActionResult GetLogData(string Sorting_Order, string Search_Data, string Filter_Value, int? Page_No, string OrderType)
        {
            var logs = workerService.GetUserLogs(CurrentUser.AccountId);

            int Size_Of_Page = 10;
            int No_Of_Page = (Page_No ?? 1);

            LogViewModel pVM = new LogViewModel();
            pVM.AccountLogs = logs.OrderByDescending(p => p.Id).ToPagedList(No_Of_Page, Size_Of_Page);
            pVM.PageCount = (int)Math.Ceiling((double)logs.Count() / Size_Of_Page);
            pVM.PageNumber = Page_No ?? 1;

            return PartialView(pVM);
        }

        public ActionResult DisplayBenefits(string Sorting_Order, string Search_Data, string Filter_Value, int? Page_No, string OrderType)
        {
            /*ViewBag.OrderType = OrderType ?? "desc";
            ViewBag.CurrentSortOrder = Sorting_Order;
            Sorting_Order = Sorting_Order ?? "FirstName";*/

            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }

            ViewBag.FilterValue = Search_Data;

            var benefitsList = workerService.GetAllWorkerBenefits(CurrentUser.PersonId);

            int Size_Of_Page = 12;
            int No_Of_Page = (Page_No ?? 1);

            BenefitsViewModel bVM = new BenefitsViewModel();
            bVM.Benefits = benefitsList.OrderByDescending(p => p.StartDate).ThenByDescending(n => n.StartDate.Month).ToPagedList(No_Of_Page, Size_Of_Page);
            bVM.PageCount = (int)Math.Ceiling((double)benefitsList.Count() / Size_Of_Page);
            bVM.PageNumber = Page_No ?? 1;

            var x = workerService.GetAccount(CurrentUser.AccountId).Person;

            bVM.PersonId = x.Id;
            bVM.FirstName = x.FirstName;
            bVM.Surname = x.Surname;
            bVM.Position = workerService.GetPositionName(x.Employment.PositionCode);
            bVM.Organization = workerService.GetOrganizationName(x.Employment.OrganiziationalUnitCode);
            ViewBag.PersonId = x.Id;

            return View(bVM);
        }

        public ActionResult Calendar()
        {
            //dodac dane do ladowania czegos
            return View();
        }

        public ActionResult WorkPanel()
        {
            return View();
        }

    }
}

HR.Web_UI/HR.Web_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Paweł Chmielewski">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui.min-1.11.1.js"></script>
    <script src="~/Scripts/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <meta name="description" content="HR helper aplication" />
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <!-- Grupowanie "marki" i przycisku rozwijania mobilnego menu -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Rozwiń nawigację</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><img style="margin-top:-10px; width:200px; height:40px;" src="~/Content/Images/logo.jpg" /></a>
                </div>
                <!-- Grupowanie elementów menu w celu lepszego wyświetlania na urządzeniach moblinych -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a href="/User/Index">Panel zadań</a></li>

                            <li><a href="#">Wyświetl monitor pracy</a></li>
                        }

                        @if (User.IsInRole("HR"))
                        {
                            <li><a href="#">Zarządzaj pracownikami</a></li>
                        }

                    </ul>

                    @*<form class="navbar-form navbar-left" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Szukaj">
                            </div>
                            <button type="submit" class="btn btn-default">Wyślij</button>
                        </form>*@

                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Witaj @User.Identity.Name<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Zarządzaj kontem", "ManageAccount", "Worker")</li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Wyloguj", "Logoff", "Account")</li>
                                    <li class="divider"></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="dropdown">
                                <a href="@Url.Action("Login","Account")" class="dropdown-toggle" data_toggle="dropdown">Zaloguj</a>
                            </li>
                        }
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Materiały<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="@Url.Action("DisplayPromotialMaterials", "Common")">Materiały promocyjne</a></li>
                                <li class="divider"></li>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li><a href="#">Materiały szkoleniowe</a></li>
                                    <li class="divider"></li>
                                }
                                <li><a href="@Url.Action("InformacjeOFirmie", "Common")">Informacje o firmie</a></li>
                                <li class="divider"></li>
                                <li><a href="@Url.Action("AboutAuthor", "Common")">Informacje o tworcy</a></li>
                            </ul>
                        </li>
                    </ul>

                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        @RenderBody()

        <img src="/Content/Images/ajax-loader.gif" id="loading-indicator" style="display:none" />

    </div>

    <div class="panel-footer" style="margin-top: 100px">

        <p style="text-align:center">&copy; 2014. Paweł Chmielewski. Praca magisterska</p>

    </div>

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script>
        //do optymalizajci
        $(document).ajaxSend(function (event, request, settings) {
            $('#loading-indicator').show();
        });

        $(document).ajaxComplete(function (event, request, settings) {
            $('#loading-indicator').hide();
        });
    </script>

    <script src="~/Scripts/Highcharts-4.0.1/js/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>
   

</body>
</html>