HR.Web_UI/HR.Web_UI/Models/ViewModels/HR/AdditionalInformationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HR.Web_UI.Models.ViewModels.HR
{
    public class AdditionalInformationViewModel
    {
        public string Facebook { get; set; }
        public string Google { get; set; }
        public string Twitter { get; set; }
        public string GoldenLine { get; set; }
        public string LinkIn { get; set; }
    }
}

HR.Web_UI/HR.Web_UI/Models/ViewModels/HR/BenefitsViewModel.cs
using HR.Core.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;

namespace HR.Web_UI.Models.ViewModels.HR
{
    public class BenefitsViewModel
    {
        public IPagedList<BenefitsProfit> Benefits { get; set; }
        public string Sorting_Order { get; set; }
        public string OrderType { get; set; }
        public string Search_Data { get; set; }
        public string Filter_Value { get; set; }
        public int? Page_No { get; set; }

        public int PageCount { get; set; }
        public int PageNumber { get; set; }

        public long PersonId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Position { get; set; }
        public string Organization { get; set; }
    }
}

HR.Web_UI/HR.Web_UI/Models/ViewModels/HR/CollegesViewModel.cs
using HR.Core.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HR.Web_UI.Models.ViewModels.HR
{
    public class CollegesViewModel
    {

        public long Id { get; set; }

        /// <summary>
        /// Nazwa uczelni. Bedzie pobierrana z slownika DIC.Colleges
        /// </summary>
        [Display(Name="Nazwa")]
        public string Name { get; set; }

        /// <summary>
        /// Kierunek na ktorym studiowal pracownik
        /// </summary>
        [Display(Name = "Kierunek studiów")]
        public string FieldOfStudy { get; set; }

        /// <summary>
        /// Specializacja
        /// </summary>
        [Display(Name = "Specializacja")]
        public string Specialization { get; set; }

        /// <summary>
        /// Tytul akademicki jaki zostal zdobyty
        /// </summary>
        [Display(Name = "Tytuł akademicki")]
        public AcademicTitleType AcademicTitle { get; set; }

        /// <summary>
        /// Tytul pracy dyplomowej
        /// </summary>
        [Display(Name = "Tytuł pracy dyplomowej")]
        public string TitleOfResearch { get; set; }

        /// <summary>
        /// Czy studiowanie zostalo zakonczone czy jest w trakcie
        /// </summary>
        [Display(Name = "Postęp")]
        public CollageProgressType Progres { get; set; }

        /// <summary>
        /// Data rozpoczecia
        /// </summary>
        [Display(Name = "Data rozpoczęcia studiów")]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Data ukonczenia
        /// </summary>
        [Display(Name = "Data zakończenia studiów")]
        public DateTime? EndDate { get; set; }
    }
}

HR.Web_UI/HR.Web_UI/Models/ViewModels/HR/ContactPersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HR.Web_UI.Models.ViewModels.HR
{
    public class ContactPersonViewModel
    {
        /// <summary>
        /// Imie osoby kontaktowej
        /// </summary>
        [Display(Name="Imię osoby kontaktowej")]
        public string FirstName { get; set; }

        /// <summary>
        /// Nazwisko osoby kontaktowej
        /// </summary>
        [Display(Name = "Nazwisko osoby kontaktowej")]
        public string Surname { get; set; }

        /// <summary>
        /// Miasto
        /// </summary>
        [Display(Name = "Miasto")]
        public string City { get; set; }

        /// <summary>
        /// Kod pocztowy
        /// </summary>
        [Display(Name = "Kod pocztowy")]
        public string PostalCode { get; set; }

        /// <summary>
        /// Ulica
        /// </summary>
        [Display(Name = "Ulica")]
        public string Street { get; set; }

        /// <summary>
        /// Numer budynku
        /// </summary>
        [Display(Name = "Numer budynku")]
        public int BuildingNumber { get; set; }

        /// <summary>
        /// Numer mieszkania
        /// </summary>
        [Display(Name = "Numer mieszkania")]
        public int ApartmentNumber { get; set; }

        /// <summary>
        /// Telefon
        /// </summary>
        [Display(Name = "Telefon")]
        public long Phone { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

HR.Web_UI/HR.Web_UI/Models/ViewModels/HR/EmploymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HR.Core.Enums;
using System.Web.Mvc;
using HR.Core.Models;
using System.ComponentModel.DataAnnotations;

namespace HR.Web_UI.Models.ViewModels.HR
{
    public class EmploymentViewModel
    {
        public EmploymentViewModel()
        {
            this.IsMonthBenefit = true;
        }

        public string Position { get; set; }

        [Display(Name="Zajmowana pozycja")]
        public List<SelectListItem> Positions { get; set; }

        [Display(Name = "Dział")]
        public string Organization { get; set; }
        public List<SelectListItem> Organizations { get; set; }

        [Display(Name = "Kierownik")]
        public string Manager { get; set; }

        public List<SelectListItem> ListOfManagers { get; set; }

        [Display(Name = "Rodzaj zatrudnienia")]
        public EmploymentType EmploymentType { get; set; }

        [Display(Name = "Data rozpoczecia współpracy")]
        public DateTime StartDate { get; set; }

        [Display(Name = "Data zakończenia współpracy")]
        public DateTime? EndDate { get; set; }

        [Display(Name = "Rodzaj umowy")]
        public ContractType  ContractType{ get; set; }

        [Display(Name = "Wymiar pracy")]
        public ContractDimensionType ContractDimension { get; set; }

        [Display(Name = "Pensja ma byc wyplacana miesiecznie?")]
        public bool IsMonthBenefit { get; set; }

        [Display(Name = "Miesieczna pensja brutto")]
        public double? MonthBenefit { get; set; }

        [Display(Name = "Godzinowe wynagrodzenie brutto")]
        public double? BenefitPerHour { get; set; }

        [Display(Name = "Nazwa banku")]
        public string BankName { get; set; }

        [Display(Name = "Adres banku")]
        public string BankAddress { get; set; }

        [Display(Name = "Numer konta")]
        public string AccountNumber { get; set; }

    }
}

HR.Web_UI/HR.Web_UI/Models/ViewModels/HR/PromotialMaterialViewModel.cs
using HR.Core.Models.RepoModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HR.Web_UI.Models.ViewModels.HR
{
    public class PromotialMaterialViewModel
    {
        public IPagedList<PromotialMaterial> Materials { get; set; }
        public string Sorting_Order { get; set; }
        public string OrderType { get; set; }
        public string Search_Data { get; set; }
        public string Filter_Value { get; set; }
        public int? Page_No { get; set; }

        public int PageCount { get; set; }
        public int PageNumber { get; set; }
    }
}

HR.Web_UI/HR.Web_UI/Controllers/HRController.cs
using HR.Core.Models;
using HR.Web_UI.Models.ViewModels.HR;
using HR.Web_UI.Services.ServicesInferface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using HR.Core.Enums;
using DotNet.Highcharts.Options;
using DotNet.Highcharts;
using DotNet.Highcharts.Helpers;
using HR.Core.Models.RepoModels;

namespace HR.Web_UI.Controllers
{
    //[Authorize(Roles="HR")]
    public class HRController : BaseController
    {
        IHRServices hrServices;

        public HRController(IHRServices _hrServices)
        {
            this.hrServices = _hrServices;
        }

        // GET: HR
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WorkPanel()
        {
            return View();
        }



        /// <summary>
        /// Caly proces powinien byc odwracalny ale nie mamy na to czasu.
        /// Powinien byc jedne viewModel do wszystkiego.
        /// Jak starczy czasu to poprawic to.
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateWorker()
        {
            return View();
        }

        public ActionResult BackToCreateWorker(PersonViewModel vm)
        {
            return View("CreateWorker",vm);
        }

        [HttpPost]
        public ActionResult CreateWorker(PersonViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Person p = new Person();

                if (hrServices.CheckEmailExist(vm))
                {
                    ModelState.AddModelError("Email", "Podany email istnieje juz w bazie.");
                    return View(vm);
                }

                p = hrServices.CreateWorker(vm);
                if (p!=null)
                {
                    Session["Person"] = p;
                    return RedirectToAction("AddWorkerAdditionalInformations");
                }
                else
                {
                    ModelState.AddModelError("", "Uzytkownik nie zostal dodany. Prosze powtorz dodanie uzytkownika");
                    return View(vm);
                }
            }
            else
            {
                return View(vm);
            }
        }

        public ActionResult AddWorkerAdditionalInformations()
        {
            ViewBag.Message = "Dodano osobe!";
            return View();
        }

        [HttpPost]
        public ActionResult AddWorkerAdditionalInfoSend(AdditionalInformationViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Person p = Session["Person"] as Person;
                AdditionalInformation ai = hrServices.CreateAdditionalInfo(vm, p);
                if(ai != null)
                {
                    return RedirectToAction("AddEmploymentInformation");
                }
                else
                {
                    ModelState.AddModelError("", "Uzytkownik nie zostal dodany. Prosze powtorz dodanie uzytkownika");
                    return View(vm);
                }
            }
            else
            {
                return View(vm);
            }
        }

        public ActionResult AddEmploymentInformation()
        {
            EmploymentViewModel eVM = new EmploymentViewModel();
            eVM.Positions = hrServices.PositionsSelectListItem();
            eVM.Organizations = hrServices.OrganizationalUnitSelectListItem();
            eVM.ListOfManagers = hrServices.GetAllManagersSelectList();
            /*eVM.Positions = new List<SelectListItem> { new SelectListItem{Text = "Java Developer", Value="1"} } ;
            eVM.Organizations = new List<SelectListItem> { new SelectListItem { Text = "JAVA TEAM", Value = "1" } };*/

            return View(eVM);
        }

        [HttpPost]
        public ActionResult AddEmploymentInformationSend(EmploymentViewModel eVM)
        {
            if (ModelState.IsValid)
            {
                Person p = Session["Person"] as Person;
                Employment e = hrServices.CreateEmployment(eVM, p);
                if (e!= null)
                {
                    return RedirectToAction("AddContactPerson");
                }
                else
                {
                    ModelState.AddModelError("","Nieznany blad");
                    return View("AddEmploymentInformation",eVM);
                }
            }
            else
            {
                eVM.Positions = hrServices.PositionsSelectListItem();
                eVM.Organizations = hrServices.OrganizationalUnitSelectListItem();
                eVM.ListOfManagers = hrServices.GetAllManagersSelectList();

                return View("AddEmploymentInformation", eVM);
            }
        }

        public ActionResult AddContactPerson()
        {
            ViewBag.Message = "Dodano informacje o zatrudnieniu pracownika!";
            return View();
        }

        [HttpPost]
        public ActionResult ContactPersonSave(ContactPersonViewModel cpVM)
        {
            if (ModelState.IsValid)
            {
                Person p = Session["Person"] as Person;
                ContactPerson cp = hrServices.CreateContactPerson(cpVM,p);
                if (cp!= null)
                {
                    return RedirectToAction("DisplaySuccessOfAddWorker");
                }
                else
                {
                    ModelState.AddModelError("", "Nieznany blad");
                    return View("AddEmploymentInformation", cpVM);
                }
            }
            else
            {
                return View("AddEmploymentInformation", cpVM);
            }
        }
        
        //potem mozna jeszcze dac zatwierdzanie osoby ze wszystko sie zgadza

        /// <summary>
        /// HR ma mozliwosc edycji danych
        /// </summary>
        /// <returns></returns>
        public ActionResult DisplaySuccessOfAddWorker()
        {
            Person p = Session["Person"] as Person;

            if (p == null)
            {
                p = new Person();
                p.Id = 6;
            }

            PersonDisplayViewModel pdVM = hrServices.GetAllPersonData(p.Id);

            if (p != null)
            {
                ViewBag.Message = "Osoba została pomyslnie dodana: " + p.FirstName + " " + p.Surname;
            }
            //globalny ViewModelZrobic
            return View(pdVM);
        }

        public ActionResult AddCollage(CollegesViewModel cVM, long Id)
        {
            if (ModelState.IsValid)
            {
                //Person p = Session["Person"] as Person;

                if(hrServices.AddNewPersonCollage(cVM,Id))
                {
                    ViewBag.Message = "Pomyślnie dodano miejsce edukacji";
                    return RedirectToAction("DisplaySuccessOfAddWorker");
                }
                else
                {
                    ModelState.AddModelError("", "Nieznany blad");
                    return View("DisplaySuccessOfAddWorker");
                }
            }
            else
            {
 
            }

            return View();
        }

        public ActionResult DisplayAllCollages(long Id)
        {
            //Person p = Session["Person"] as Person;

#warning Uwaga trzba inna akcje dac zeby wyswietlac szczególy pracownika

            var x = hrServices.GetAllColleges(Id);

            return PartialView("_LearnHistory",x);
        }

        public ActionResult AddJob(EmploymentsViewModel cVM)
        {

            if (ModelState.IsValid)
            {
                //Person p = Session["Person"] as Person;
                
                if (hrServices.AddNewPersonJob(cVM, cVM.Id))
                {
                    ViewBag.Message = "Pomyślnie dodano miejsce zatrudnienia";
                    return RedirectToAction("DisplaySuccessOfAddWorker");
                }
                else
                {
                    ModelState.AddModelError("", "Nieznany blad");
                    return View("DisplaySuccessOfAddWorker");
                }
            }
            else
            {

            }

            return View();
        }

        public ActionResult DisplayAllJobs(long Id)
        {
#warning Uwaga trzba inna akcje dac zeby wyswietlac szczególy pracownika
            //Person p = Session["Person"] as Person;

            var x = hrServices.GetAllJobs(Id);

            return PartialView("_EmploymentHistory",x);
        }

        public ActionResult DisplayAllTranings(long Id)
        {
            var x = hrServices.GetAllTrainings(Id);

            return PartialView("_TraningsHistory",x);
        }

        public ActionResult AddTraning(TraningsViewModel tVM, long Id)
        {
            if (ModelState.IsValid)
            {

                if (hrServices.AddNewPersonTrainings(tVM, Id))
                {
                    ViewBag.Message = "Pomyślnie dodano szkolenie/certyfkiacje";
                    return RedirectToAction("DisplaySuccessOfAddWorker");
                }
                else
                {
                    ModelState.AddModelError("", "Nieznany blad");
                    return View("DisplaySuccessOfAddWorker");
                }
            }
            else
            {

            }

            return View();
        }


        public ActionResult DisplayListOfWorkers(string Sorting_Order, string Search_Data, string Filter_Value, int? Page_No, string OrderType)
        {
            ViewBag.OrderType = OrderType ?? "desc";
            ViewBag.CurrentSortOrder = Sorting_Order;
            Sorting_Order = Sorting_Order ?? "FirstName";

            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }

            ViewBag.FilterValue = Search_Data;

HR.Web_UI/HR.Web_UI/Views/HR/AddCollage.cshtml
@model HR.Web_UI.Models.ViewModels.HR.CollegesViewModel

 @using (Ajax.BeginForm("AddCollage", "HR",
            new AjaxOptions { UpdateTargetId = "learning", LoadingElementId = "loading-indicator"}
            , new {  method = "POST" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FieldOfStudy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FieldOfStudy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FieldOfStudy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Specialization, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Specialization, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specialization, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AcademicTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.AcademicTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AcademicTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TitleOfResearch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TitleOfResearch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitleOfResearch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Progres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Progres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Progres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

HR.Web_UI/HR.Web_UI/Views/HR/AddEmploymentInformation.cshtml
@model HR.Web_UI.Models.ViewModels.HR.EmploymentViewModel

@{
    ViewBag.Title = "Krok 3";
}

<h2 class="col-lg-offset-5 m_b_30">Dodaj pracownika - zatrudnienie</h2>

<div id="formContener" class="col-lg-6 col-lg-offset-3 form-group">
    @using (Ajax.BeginForm("AddEmploymentInformationSend", "HR",
            new AjaxOptions { UpdateTargetId = "formContener", LoadingElementId = "loading-indicator", LoadingElementDuration = 10000 }
            , new { enctype = "multipart/form-data", method = "POST" }))
    {
        <div class="panel panel-default">
            <div class="panel-heading">Dane zatrudnienia</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.Position)</span>
                    @Html.DropDownListFor(p => p.Position, Model.Positions, new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(p => p.Position)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.Organization)</span>
                    @Html.DropDownListFor(p => p.Organization, Model.Organizations, new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(p => p.Organization)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.Manager)</span>
                    @Html.DropDownListFor(p => p.Manager, Model.ListOfManagers, new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(p => p.Manager)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.EmploymentType)</span>
                    @Html.EnumDropDownListFor(p => p.EmploymentType, new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(p => p.EmploymentType)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.StartDate)</span>
                    <input type="date" class="form-control" placeholder="Data rozpoczecia" name="StartDate" id="StartDate">

                </div>
                @Html.ValidationMessageFor(p => p.StartDate)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.EndDate)</span>
                    <input type="date" class="form-control" placeholder="Data zakonczenia" name="EndDate" id="EndDate">

                </div>
                @Html.ValidationMessageFor(p => p.EndDate)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.ContractType)</span>
                    @Html.EnumDropDownListFor(p => p.ContractType, new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(p => p.ContractType)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.ContractDimension)</span>
                    @Html.EnumDropDownListFor(p => p.ContractDimension, new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(p => p.ContractDimension)<br />


                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.IsMonthBenefit)</span>
                    @Html.CheckBoxFor(p => p.IsMonthBenefit)
                </div>
                

                <div class="input-group" id="MonthBenefitCH">
                    <span class="input-group-addon">@Html.LabelFor(p => p.MonthBenefit)</span>
                    <input type="text" class="form-control" placeholder="Pensja miesieczna brutto" name="MonthBenefit" id="MonthBenefit">

                </div>
                @Html.ValidationMessageFor(p => p.MonthBenefit)<br />

                <div class="input-group" id="BenefitPerHourCH">
                    <span class="input-group-addon">@Html.LabelFor(p => p.BenefitPerHour)</span>
                    <input type="text" class="form-control" placeholder="Pensja placona na godzine brutto" name="BenefitPerHour" id="BenefitPerHour">

                </div>
                @Html.ValidationMessageFor(p => p.BenefitPerHour)<br />

            </div>
        </div>

        
        
        <div class="panel panel-default">
            <div class="panel-heading">Dane bankowe</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.BankName)</span>
                    <input type="text" class="form-control" placeholder="Nazwa banku" name="BankName" id="BankName">

                </div>
                @Html.ValidationMessageFor(p => p.BankName)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.BankAddress)</span>
                    <input type="text" class="form-control" placeholder="Adress banku" name="BankAddress" id="BankAddress">

                </div>
                @Html.ValidationMessageFor(p => p.BankAddress)<br />

                <div class="input-group">
                    <span class="input-group-addon">@Html.LabelFor(p => p.AccountNumber)</span>
                    <input type="text" class="form-control" placeholder="Numer konta" name="AccountNumber" id="AccountNumber">

                </div>
                @Html.ValidationMessageFor(p => p.AccountNumber)<br />
            </div>
        </div>

        



        <input type="submit" class="btn col-lg-offset-5" value="Przejdz do kroku 4" />
    }
</div>

<script>
    jQuery(document).ready(function () {
            if ($("#IsMonthBenefit").is(':checked')) {
                $("#MonthBenefitCH").show();
                $("#BenefitPerHourCH").hide();
            }
            else
            {
                $("#MonthBenefitCH").hide();
                $("#BenefitPerHourCH").show();
            }

            $('#IsMonthBenefit').change(function () {
                if ($("#IsMonthBenefit").is(':checked')) {
                    $("#MonthBenefitCH").show();
                    $("#BenefitPerHourCH").hide();
                }
                else {
                    $("#MonthBenefitCH").hide();
                    $("#BenefitPerHourCH").show();
                }
            });

    });
</script>

HR.Web_UI/HR.Web_UI/Views/HR/AddPromotialMaterial.cshtml
@model HR.Core.Models.RepoModels.PromotialMaterial

@using (Ajax.BeginForm("AddPromotialMaterial", "HR",
            new AjaxOptions { UpdateTargetId = "working", LoadingElementId = "loading-indicator" }
            , new { enctype = "multipart/form-data", method = "POST" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhotoTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhotoTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="input-group col-lg-6" style="float:none">
            <span class="input-group-addon">@Html.LabelFor(p => p.Photo)</span>
        </div>
        <input type="file" name="Photo" class="btn" id="Photo" onchange="ShowpImagePreview(this);" />
        <img id="imgprvw" alt="uploaded image preview" class="h_300 w_200" style="float:left" />
        <br />
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<script type="text/javascript">
    function ShowpImagePreview(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#imgprvw').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

HR.Web_UI/HR.Web_UI/Views/HR/ChartTest.cshtml
@model DotNet.Highcharts.Highcharts

@(Model)

@(Model)